jnothman/UpSetPlot

upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Smoke test plotting

---

examples/plot_generated.py
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Rename order to sort_by etc.

---

upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Fixes #26 
Partial fix for #12 
needs tests

Add ability to control element_size

---

examples/plot_vertical.py
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Fixes #2
Needs tests, examples and comments

Reorientation as vertical/horizontal

---

CHANGELOG.rst
README.rst
doc/api.rst
upsetplot/__init__.py
upsetplot/data.py
upsetplot/tests/test_data.py

More user friendly loading format

---

CHANGELOG.rst
README.rst
doc/requirements.txt
examples/plot_boston.py
setup.cfg
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

resolves #9; supersedes and resolves #25

add_catplot to produce intersection plots other than cardinality

---

README.rst
upsetplot/data.py
upsetplot/tests/test_data.py

FIX from_memberships now returns Series when data is series-like

---

upsetplot/plotting.py

This commit fixes https://github.com/jnothman/UpSetPlot/issues/53

adding intersections ylabel

---

doc/api.rst
upsetplot/__init__.py
upsetplot/data.py
upsetplot/tests/test_data.py

Fixes #56 (at least in some ways. other aspects are covered by other issues). Ping @samneuron

From contents

---

CHANGELOG.rst
examples/plot_boston.py
setup.cfg
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

This is intended to make the `sum_over` functionality more user-friendly and legible, working towards more sensible default behaviour.
Fixes #62
TO DO:

Introduce a subset_size parameter

---

CHANGELOG.rst
README.rst
doc/api.rst
examples/plot_generated.py
examples/plot_vertical.py
upsetplot/__init__.py
upsetplot/data.py
upsetplot/tests/test_data.py
upsetplot/tests/test_upsetplot.py

Not sure if generate_counts is the best name.
Fixes #68 
Resolves #51

Replace generate_data with generate_counts and generate_samples

---

CHANGELOG.rst
upsetplot/plotting.py

ENH Efficiency for sort_by='degree'

---

upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Should fix #74
TODO: add tests

Allow truthy indices in input

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Fix incorrect percentage denominator

---

examples/plot_boston.py
upsetplot/plotting.py

Fix order of catplots in vertical orientation

---

upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

xlim needs to start at < 0; expected values were off by one
Fixes #124
Closes #125

Fix a regression introduced in #106

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

TODO: can we add a test to ensure no overlap of totals plots?

Fix undersized xlabel space

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Supersedes and closes #96
Fixes #99

Given data order

---

CHANGELOG.rst
examples/plot_hide.py
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Filtering on subset and degree size

---

CHANGELOG.rst
examples/plot_theming.py
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Setting colors and example of style sheets

---

.travis.yml
CHANGELOG.rst
examples/plot_discrete.py
setup.py
upsetplot/plotting.py
upsetplot/tests/test_upsetplot.py

Resolves #136, thanks @amitfenn and @yollct for the inspiration!
TODO:

add_stacked_bars feature

---

doc/api.rst
upsetplot/__init__.py
upsetplot/plotting.py
upsetplot/reformat.py
upsetplot/tests/test_reformat.py

Abstract out a query function

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/reformat.py
upsetplot/tests/test_upsetplot.py

Add include_empty_subsets

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/reformat.py
upsetplot/tests/test_upsetplot.py

Options to sort in reverse

---

setup.py

Fixes https://github.com/jnothman/UpSetPlot/issues/232

Update setup.py to handle pytest-runner deprecation etc

---

upsetplot/plotting.py
upsetplot/tests/test_data.py

Fix warning due to styling dtyles, and fix column dtype test failure

---

.github/workflows/lint.yml
CHANGELOG.rst
LICENSE
doc/conf.py

Fix lint CI workflow name

---

examples/plot_highlight.py

Example of highlight by degree

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/reformat.py
upsetplot/tests/test_upsetplot.py

Add max_subset_rank

---

examples/plot_customize_after_plot.py

set_xlabel example for totals plot

---

examples/plot_generated.py

Example showing rcParams for smaller font size

---

CHANGELOG.rst
examples/plot_customize_after_plot.py
upsetplot/plotting.py

The change to enable axis labelling didn't work and won't without resolving https://github.com/jnothman/UpSetPlot/issues/259
Fixes #258

Partially revert e938a672345c7fdac6baea0171617c8196ed3b1b

---

CHANGELOG.rst
upsetplot/plotting.py
upsetplot/reformat.py
upsetplot/tests/test_upsetplot.py

Allow specification of subset sizes as percentage

---

CHANGELOG.rst
upsetplot/plotting.py

Call align_ylabels on subset plots
